services:
  nf:
    image: apache/nifi:latest
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    ports:
      - "8443:8443"
    volumes:
      - /Users/antonshishkov/Documents/nifi-files:/opt/nifi/nifi-current/data
